version: 0.2
           
phases:
  install:
    commands:
      - gem install bundler jekyll
  pre_build:
    commands:
      - jekyll --version
      - bundler --version
      - gem update bundler
      - jekyll --version
      - bundler --version            
      - cd codebuild-jekyll-test
  build:
    commands:
      - jekyll b

      

