version: 0.2
           
phases:
  install:
    commands:
      - gem install jekyll
  pre_build:
    commands:
      - jekyll --version
      - cd codebuild-jekyll-test
      - pwd      
  build:
    commands:
      - pwd      
      - jekyll b

      

