version: 0.2
           
phases:
  install:
    commands:
      - gem install jekyll
  pre_build:
    commands:
      - jekyll --version
      - bundler --version      
      - cd codebuild-jekyll-test
  build:
    commands:
      - jekyll b

      

