version: 0.2
           
phases:
  install:
    commands:
      - gem install bundler jekyll
  pre_build:
    commands:
      - jekyll --version
      - pwd
      - cd codebuild-jekyll-test
  build:
    commands:
      - jekyll b

      

