version: 0.2
           
phases:
  install:
    commands:
      - gem install bundler jekyll
      - gem install minima      
  pre_build:
    commands:
      - jekyll --version
      - bundler --version                  
      - cd codebuild-jekyll-test
  build:
    commands:
      - bundle exec jekyll b
  post_build:
    commands:
      - cd _site
      - pwd
artifacts:
  files:
    - 'codebuild-jekyll-test/_site/**/*'
  name: jekyll-sample-artifacts
  discard-paths: no

      

